# Server Configuration
server:
  port: 8080

# Flowise API Configuration
# flowise:
#   api:
#     endpoints:
#       api-doc-generator: http://124.222.232.31:3000/api/v1/prediction/535f90a0-0179-4c76-bc61-d81cc9c3ec8f
#       workflow-generator: http://124.222.232.31:3000/api/v1/prediction/659d7ac6-156b-4c95-8cda-908bfe41cdc5
#       entity-generator: http://124.222.232.31:3000/api/v1/prediction/b1c861fd-4e3d-44d4-bacf-72548da354b3
#       data-sql-generator: http://124.222.232.31:3000/api/v1/prediction/dc5d38e2-6ef4-45d6-8629-e9076b9e7c51
#   api:
#     auth:
#       token: B1O4BXKWOTP_47B1zPKFyR-K6ytVG2vf87nTgXsrDds

# Redis Configuration
spring:
  data:
    redis:
      host: 119.29.206.157
      port: 6379
      password: 123456
      database: 0
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

# Memory Management Configuration
memory:
  max:
    chat:
      history: 50
  ttl:
    hours: 24
  ttl:
    minutes: 1440

# Logging Configuration
logging:
  level:
    root: INFO
    com.example: DEBUG
    com.example.ai.deployment: TRACE
    org.springframework.web: DEBUG
    org.hibernate: INFO
  file:
    name: logs/application.log
    path: d:/code/flowise/autoCICD-langchain4j/logs
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"